pipeline:
    build:
        image: hashicorp/terraform:0.11.14
        commands:
            - terraform version
            - terraform validate -check-variables="false"
            - terraform fmt -check=true
